### ISSUE TITLE
Hinzufügen einer CODEOWNERS Datei

### ISSUE THREAD

**Issue by wlitke** [wlitke/translator#10]
Damit bei Pull Requests per Default ein Benutzer eingetragen wird (der Benachrichtigung wegen) muss eine CODEOWNERS Datei angelegt werden.

Datei Dokumentation: https://docs.github.com/en/enterprise/2.18/user/github/creating-cloning-and-archiving-repositories/about-code-owners

Für dieses Projekt wäre folgender Datei-Inhalt ausreichend:

```
# This is a comment.
# Each line is a file pattern followed by one or more owners.

# These owners will be the default owners for everything in
# the repo. Unless a later match takes precedence,
# @global-owner1 and @global-owner2 will be requested for
# review when someone opens a pull request.
*       @wlitke
```

**Comment by eppstephan** [comment]
Added CODEOWNERS file in the root of the repo

**Comment by eppstephan** [comment]
@wlitke Geschlossen, ich hoffe das war in Ordnung
