### ISSUE TITLE
Einladung für Microsoft Azure Account annehmen

### ISSUE THREAD

**Issue by wlitke** [wlitke/translator#6]
Du wirst eine Microsoft Azure Einladungs-Email erhalten (siehe unten Beispiel-Email).
Bitte folge der Einladung und stelle sicher, dass du Zugriff auf das Azure Portal ([https://portal.azure.com](https://portal.azure.com)) erhältst

------------------------
**Beispiel-Email:**

**Absender**: Microsoft Invitations on behalf of delightsolutions <invites@microsoft.com>
**Betreff**: delightsolutions invited you to access applications within their organization
**Inhalt**:

![Image](https://user-images.githubusercontent.com/113239363/194294956-8b3a7881-c624-4828-99a9-bcf0df1ab18d.png)

**Comment by wlitke** [comment]
Du wirst eine Microsoft Azure Einladungs-Email erhalten (siehe unten Beispiel-Email).
Bitte folge der Einladung und stelle sicher, dass du Zugriff auf das Azure Portal ([https://portal.azure.com](https://portal.azure.com)) erhältst


------------------------

Absender: Microsoft Invitations on behalf of delightsolutions <invites@microsoft.com>
Betreff: delightsolutions invited you to access applications within their organization
Inhalt:

![Image](https://user-images.githubusercontent.com/113239363/194294956-8b3a7881-c624-4828-99a9-bcf0df1ab18d.png)

**Comment by eppstephan** [comment]
Nicht sicher, ob ich wirklich schon Zugriff habe als angemeldeter Benutzer - es scheint allerdings so.

**Comment by wlitke** [comment]
@eppstephan Wenn du nach dem Login eine ähnliche Oberfläche wie die im Screenshot siehst (inkl. rot markierter Ressource), hast du Zugriff. Du kannst ja mal auf die Ressource "ctrans" klicken und dich dann etwas umsehen. Links im Menü findest du die Option "Monitoring > Metrics", welche dir die Möglichkeit gibt den Service Verbrauch zu prüfen. Würdest du das bitte nochmal kurz checken. (PS: Ich habe den Issue Status wieder auf "In Progress" gesetzt)

![Image](https://user-images.githubusercontent.com/113239363/194486380-3f2c9718-c774-4290-9c13-b90d5cbff839.png)

**Comment by wlitke** [comment]
@eppstephan Wie besprochen funktioniert dein Account nun ordnungsgemäß. Aus unbekannten Gründen hat die erste Einladung zu einem falschen "Tenant" geführt bzw. wurde dein Account mit einem falschen Tenant verknüpft.
