### ISSUE TITLE
Lagere den Subscription-Key in die Konfigurationsdatei aus

### ISSUE THREAD

**Issue by wlitke** [wlitke/translator#7]
Momentan wird der Subscription-Key für den Speech Service im Code direkt angegeben (via `SpeechTranslationConfig.FromSubscription("", "westeurope");`). Um das Projekt automatisiert bauen zu können (und den Key von außen reinzugeben), wäre es besser den Key aus der "App.config Datei zu lesen.

**Achtung**: Bitte denke daran, den Subscription-Key vor dem Git-Commit durch einen Dummy-Platzhalter zu ersetzen. Keys sollten niemals im Repository gespeichert werden.

**Implementierungs-Tipp**: Die Konfiguration-Funktionalität wird durch die `ConfigurationManager` Klasse ermöglicht (siehe Beispiel-Code: https://learn.microsoft.com/de-de/dotnet/api/system.configuration.configurationmanager.appsettings?view=dotnet-plat-ext-6.0)

**Comment by wlitke** [comment]
@eppstephan Ergänzender Hinweis: Ab jetzt solltest du für jedes Issue einen separaten Branch anlegen, der anschließend geprüft (Review) und dann in den "main" Branch überführt wird. Ich würde im Moment den Overhead gering halten und lediglich einen weiteren Branch anlegen und nicht wie im regulären Fall zuerst einen Feature Branch und dann einen User/Develop Branch.
Ich schlage vor, den Branch nach folgendem Pattern zu benennen: <IssueId>-<KurzBezeichner>.
In diesem Fall würde der Branch z. B. "7-subscription-key-auslagerung" lauten.

**Comment by wlitke** [comment]
Wenn du die Branch-Handhabung nochmal besprechen möchtest oder wenn wir das mal zusammen machen sollen, dann ruf einfach kurz durch.

**Comment by wlitke** [comment]
@eppstephan Tipp am Rande: Auf folgender Seite (insbesondere Sektion "Secrets") wird erklärt, wie man App.config Teile in separate Dateien ausgliedert, um diese lokal zu verwalten und somit nicht in ein Git Repository übertragen zu müssen.

**Comment by eppstephan** [comment]
@wlitke Geschlossen, ich hoffe das war in Ordnung
